"""Transverse-field XY model of the fixed-depth Hamiltonian simulation benchmark (paper App. F).

The hard-coded so(2n) Pauli mapping of Eq. (F11) and the model Hamiltonians used by
:mod:`kak_tools.full_workflows`. The generic route for other models is
:func:`kak_tools.map_simple_to_irrep` or :func:`kak_tools.kak_decomposition`.
"""

from itertools import combinations, product

import numpy as np
import pennylane as qml
from pennylane import X, Y, Z
from pennylane.pauli import PauliWord

from .map_to_irrep import irrep_dot, make_signs


def make_so_2n(n):
    """Create all Pauli words for the reducible so(2n) representation implemented
    by the transverse field XY model, i.e., generated by XX couplings, YY couplings, and
    single-qubit Z operators."""
    algebra = [
        PauliWord({w: P1, v: P2} | dict.fromkeys(range(w + 1, v), "Z"))
        for w, v in combinations(range(n), r=2)
        for P1, P2 in product("XY", repeat=2)
    ]
    algebra += [PauliWord({w: "Z"}) for w in range(n)]
    return algebra


def make_so_2n_horizontal_mapping(n):
    """Create a default reducible-to-irreducible mapping for some horizontal operators
    in a BDI decomposition of so(2n). The mapped operators are XX couplings, YY couplings,
    and single-qubit Z operators."""
    mapping = {(i, i + n): PauliWord({i: "Z"}) for i in range(n)}
    mapping |= {(i, i + n + 1): PauliWord({i: "X", i + 1: "X"}) for i in range(n - 1)}
    mapping |= {(i, i + n - 1): PauliWord({i - 1: "Y", i: "Y"}) for i in range(1, n)}
    return mapping


def make_so_2n_full_mapping(n):
    """Return the TF-XY so(2n) Pauli mapping of Eq. (F11) with its signs.

    Contains :func:`make_so_2n_horizontal_mapping`; XX, YY and Z terms are horizontal
    for BDI(n, n). The signs are those of :func:`make_signs`, so ``i * word`` maps to
    ``2 * sign * (E_ij - E_ji)``: -1 for the Z fields at ``(i, n + i)`` (Eq. F14) and the
    YX strings at ``(n + i, n + j)``, +1 elsewhere.
    """
    upper_left, lower_right, upper_right, lower_left = {}, {}, {}, {}
    for i, j in combinations(range(n), 2):
        chain = dict.fromkeys(range(i + 1, j), "Z")
        upper_left[(i, j)] = PauliWord({i: "X", j: "Y"} | chain)
        lower_right[(n + i, n + j)] = PauliWord({i: "Y", j: "X"} | chain)
        upper_right[(i, n + j)] = PauliWord({i: "X", j: "X"} | chain)
        lower_left[(j, n + i)] = PauliWord({i: "Y", j: "Y"} | chain)
    mapping = upper_left | lower_right | upper_right | lower_left
    mapping |= {(i, n + i): PauliWord({i: "Z"}) for i in range(n)}
    return mapping, make_signs(mapping, 2 * n, "BDI")


def make_so_2n_full_mapping_str(n):
    """Return TF-XY rotation planes as (compressed Pauli string, sign) entries.

    Numbers count leading identities, intervening Z factors and trailing identities.
    The signs agree with :func:`make_so_2n_full_mapping`.
    """
    upper_left, lower_right, upper_right, lower_left = {}, {}, {}, {}
    for i, j in combinations(range(n), 2):
        upper_left[(i, j)] = (f"{i}X{j - i - 1}Y{n-j-1}", 1)
        lower_right[(n + i, n + j)] = (f"{i}Y{j - i - 1}X{n-j-1}", -1)
        upper_right[(i, n + j)] = (f"{i}X{j - i - 1}X{n-j-1}", 1)
        lower_left[(j, n + i)] = (f"{i}Y{j - i - 1}Y{n-j-1}", 1)
    mapping = upper_left | lower_right | upper_right | lower_left
    mapping |= {(i, n + i): (f"{i}Z{n - i - 1}", -1) for i in range(n)}

    return mapping


def _make_tfXY_coeffs(n, coefficients, rng=None):
    """Return normalized ``(alphas, betas, gammas)`` for the XX, YY and Z terms of Eq. (F1).

    ``rng`` seeds the random choices, see :func:`numpy.random.default_rng`.
    """
    rng = np.random.default_rng(rng)
    choice = coefficients if isinstance(coefficients, str) else None
    if choice == "random":
        alphas = rng.normal(0.6, 1.0, size=n - 1)
        betas = rng.normal(0.3, 1.2, size=n - 1)
        gammas = rng.normal(0.0, 0.3, size=n)
    elif choice == "random TF":
        alphas = np.ones(n - 1)
        betas = np.ones(n - 1)
        gammas = rng.normal(0.0, 0.3, size=n)
    elif choice == "uniform":
        alphas = np.ones(n - 1)
        betas = np.ones(n - 1)
        gammas = np.ones(n)
    else:
        raise ValueError(
            f"coefficients must be 'random', 'random TF' or 'uniform', got {coefficients!r}."
        )

    norm = np.linalg.norm(np.concatenate([alphas, betas, gammas]))
    return alphas / norm, betas / norm, gammas / norm


def make_tfXY_hamiltonian_qubits(n, coefficients="random", rng=None):
    """Create the transverse-field XY model Hamiltonian on n qubits,
    in its original representation on qubits.
    The Hamiltonian is normalized to trace norm 1.
    """
    alphas, betas, gammas = _make_tfXY_coeffs(n, coefficients, rng)
    coeffs = np.concatenate([alphas, betas, gammas])
    couplings = [X(w) @ X(w + 1) for w in range(n - 1)] + [Y(w) @ Y(w + 1) for w in range(n - 1)]
    Zs = [Z(w) for w in range(n)]
    generators = couplings + Zs
    H = qml.dot(coeffs, generators)
    generators = [next(iter(op.pauli_rep)) for op in generators]
    return H, generators, coeffs


def make_tfXY_hamiltonian_irrep(n, coefficients="random", rng=None):
    """Create the transverse-field XY model Hamiltonian on n qubits,
    represented in a free-fermionic picture as 2n x 2n matrix.
    This function uses the hardcoded mapping from the manuscript for this particular
    model, so that ``expm(t * H_irrep)`` represents ``exp(i * t * H)`` on qubits.
    The Hamiltonian is normalized to trace norm 1.
    """
    _, generators, coeffs = make_tfXY_hamiltonian_qubits(n, coefficients, rng)
    mapping, signs = make_so_2n_full_mapping(n)
    return irrep_dot(coeffs, generators, mapping, signs, n=2 * n, invol_type="BDI")
